# Generated by Django 4.2.2 on 2023-07-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0003_tag_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
